name: Test Package

on:
  push:
    branches:
    - dev
    - main
    - feat/*
    - fix/*
    - refactor
  pull_request:
    branches:
    - main
    - feat/*
    - fix/*
    - refactor

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest .
    - name: Test with pytest
      run: |
        python -m pytest
